/**
 * The conversation, kept so a stopped run can be picked up again.
 *
 * `dsh continue` exists because of what the real runs did: seven of nine stopped
 * at a limit with the work half-finished, and there was no way to carry on
 * except to start the whole thing again from the task file. Starting again is
 * not "continuing": the agent re-reads everything it already knew, pays for
 * every token a second time, and can go a different way and land somewhere
 * inconsistent with the half-applied change already in the worktree.
 *
 * So the message list is written down as it grows, one file per run, and a
 * continuation is handed it back.
 *
 * **The reason this preserves the cache.** DeepSeek bills a prompt prefix that
 * matches an earlier request at about a tenth of the price. The prefix is
 * compared byte for byte, so a continuation has to send exactly the same
 * messages in exactly the same order, starting from the system prompt. Anything
 * that rebuilt the conversation — from the event log, from a summary, from the
 * agent's own notes — would be a *new* conversation that happens to know things,
 * and would bill as one. Reusing the array the previous run ended with is the
 * only version that hits.
 *
 * A run's transcript is written on a best-effort basis: there is no job worth
 * failing over a file that is only there to make the next run cheaper.
 */

import fs from 'node:fs';
import path from 'node:path';
import { harnessHome } from './config.js';
import type { ChatMessage } from './deepseek.js';

/** Where a run's conversation is kept. */
export function transcriptsDir(): string {
  return path.join(harnessHome(), 'transcripts');
}

export function transcriptFile(runId: string): string {
  // A run id is generated by the daemon and looks like `run-1a2b3c4d`, but this
  // is the one place a caller-supplied string reaches a file path, so anything
  // that is not that shape is refused rather than joined.
  if (!/^[A-Za-z0-9_-]+$/.test(runId)) {
    throw new Error(`${runId} is not a run id`);
  }
  return path.join(transcriptsDir(), `${runId}.json`);
}

export function writeTranscript(runId: string, messages: ChatMessage[]): void {
  try {
    const file = transcriptFile(runId);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    // Written to a temporary name and renamed, so a continuation can never read
    // a half-written conversation. A rename is atomic on both platforms this
    // runs on; an interrupted write would otherwise leave truncated JSON, which
    // reads as "no transcript" and silently loses the cache.
    const temporary = `${file}.tmp`;
    fs.writeFileSync(temporary, JSON.stringify(messages), 'utf8');
    fs.renameSync(temporary, file);
  } catch {
    // Best effort. Losing the transcript costs a continuation its cache, and
    // failing the run over that would cost it everything.
  }
}

export interface LoadedTranscript {
  messages: ChatMessage[];
  /** Why it could not be used, when it could not be. */
  failure: string | null;
}

/**
 * The conversation a run ended with, or why there is not one.
 *
 * The failure is returned rather than thrown because the caller's decision is
 * "continue without the history" or "refuse", and it can only make that decision
 * if it is told which happened.
 */
export function readTranscript(runId: string): LoadedTranscript {
  let raw: string;
  try {
    raw = fs.readFileSync(transcriptFile(runId), 'utf8');
  } catch {
    return { messages: [], failure: `no transcript for ${runId}` };
  }
  try {
    const parsed = JSON.parse(raw) as unknown;
    if (!Array.isArray(parsed) || parsed.length === 0) {
      return { messages: [], failure: `the transcript for ${runId} is empty` };
    }
    return { messages: parsed as ChatMessage[], failure: null };
  } catch {
    return { messages: [], failure: `the transcript for ${runId} is not readable` };
  }
}
